### ISSUE TITLE
Merge into original `pitchfork` repository?

### ISSUE THREAD

**Issue by fortes** [tejassharma96/pitchfork_api#3]
Can we merge this into https://github.com/michalczaplinski/pitchfork/  ? 

Would be good to publish this package with the nice `pitchfork` name

**Comment by johnwmillr** [comment]
Yes, let's do it. But this repository isn't a fork of the original `pitchfork` project, right? So I think we'll have to handle the merge manually (without a pull request). Shouldn't be too difficult though, I imagine.

**Comment by tejassharma96** [comment]
Yep, should be decently simple. I’d say just copy over pitchfork.py and the travis ci and that’d probably be all. I’d do it but I’m travelling this week and gonna have spotty laptop access at best - will be out most of the day.

**Comment by fortes** [comment]
OK, PR here if someone can give a second look: https://github.com/michalczaplinski/pitchfork/pull/15

**Comment by fortes** [comment]
Done here: https://github.com/michalczaplinski/pitchfork/pull/15
